import type { Question } from '@/lib/types';
import { makeMcq } from '@/lib/competitive-exam/question-factory';

function s(
  topicKey: string,
  topicSlug: string,
  idx: number,
  text: string,
  o: [string, string, string, string],
  letter: 'A' | 'B' | 'C' | 'D',
  difficulty: Question['difficulty'] = 'medium',
): Question {
  return makeMcq({
    id: `static-${topicKey}-${idx}`,
    topicSlug,
    difficulty,
    question_text: text,
    options: o,
    correctLetter: letter,
    explanation: null,
  });
}

/** Curated factual / language / computer literacy items (mixed competitive style). */
export const STATIC_SCIENCE: Question[] = [
  s('sci', 'competitive-science', 1, 'SI unit of force is:', ['Newton', 'Joule', 'Watt', 'Pascal'], 'A', 'easy'),
  s('sci', 'competitive-science', 2, 'Speed of light in vacuum is approximately:', ['3×10⁸ m/s', '3×10⁶ m/s', '3×10¹⁰ m/s', '340 m/s'], 'A', 'easy'),
  s('sci', 'competitive-science', 3, 'Human red blood cells are produced mainly in:', ['Bone marrow', 'Liver', 'Spleen', 'Kidneys'], 'A', 'medium'),
  s('sci', 'competitive-science', 4, 'Photosynthesis primarily occurs in:', ['Chloroplasts', 'Mitochondria', 'Ribosomes', 'Golgi bodies'], 'A', 'easy'),
  s('sci', 'competitive-science', 5, 'Which gas is most abundant in Earth’s atmosphere?', ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Argon'], 'A', 'easy'),
  s('sci', 'competitive-science', 6, 'DNA double helix structure was described by:', ['Watson & Crick', 'Pasteur', 'Darwin', 'Mendel'], 'A', 'easy'),
  s('sci', 'competitive-science', 7, 'Deficiency of Vitamin D in children may lead to:', ['Rickets', 'Scurvy', 'Beriberi', 'Night blindness'], 'A', 'medium'),
  s('sci', 'competitive-science', 8, 'Heart is covered by:', ['Pericardium', 'Peritoneum', 'Pleura', 'Meninges'], 'A', 'hard'),
  s('sci', 'competitive-science', 9, 'Which blood group is called universal donor?', ['O negative', 'AB positive', 'A positive', 'B negative'], 'A', 'medium'),
  s('sci', 'competitive-science', 10, 'Refraction of light is responsible for:', ['Rainbow formation', 'Echo', 'Sound beats', 'Electromagnetic induction'], 'A', 'medium'),
  s('sci', 'competitive-science', 11, 'The powerhouse of the cell is:', ['Mitochondria', 'Nucleus', 'Vacuole', 'Lysosome'], 'A', 'easy'),
  s('sci', 'competitive-science', 12, 'Which planet is known as the Red Planet?', ['Mars', 'Venus', 'Jupiter', 'Saturn'], 'A', 'easy'),
  s('sci', 'competitive-science', 13, 'Sound cannot travel through:', ['Vacuum', 'Water', 'Steel', 'Air'], 'A', 'easy'),
  s('sci', 'competitive-science', 14, 'Which organelle is found mostly in plant cells and provides rigidity?', ['Cell wall', 'Centriole', 'Lysosome', 'Flagellum'], 'A', 'easy'),
  s('sci', 'competitive-science', 15, 'Which vitamin is synthesized in skin with sunlight?', ['Vitamin D', 'Vitamin A', 'Vitamin K', 'Vitamin E'], 'A', 'easy'),
  s('sci', 'competitive-science', 16, 'Which mirror is used by dentists for enlarged images?', ['Concave mirror', 'Convex mirror', 'Plane mirror', 'Parabolic mirror'], 'A', 'medium'),
  s('sci', 'competitive-science', 17, 'Which instrument measures atmospheric pressure?', ['Barometer', 'Manometer', 'Hygrometer', 'Anemometer'], 'A', 'medium'),
  s('sci', 'competitive-science', 18, 'Which disease is caused by Plasmodium?', ['Malaria', 'Cholera', 'Typhoid', 'Tuberculosis'], 'A', 'easy'),
  s('sci', 'competitive-science', 19, 'Which lens corrects myopia?', ['Concave lens', 'Convex lens', 'Cylindrical lens', 'Bifocal lens'], 'A', 'medium'),
  s('sci', 'competitive-science', 20, 'Boiling point of water at sea level is:', ['100°C', '0°C', '37°C', '212°C'], 'A', 'easy'),
  s('sci', 'competitive-science', 21, 'Which blood vessel carries oxygenated blood from lungs?', ['Pulmonary vein', 'Pulmonary artery', 'Vena cava', 'Hepatic vein'], 'A', 'hard'),
  s('sci', 'competitive-science', 22, 'In the water cycle, water vapour turns to liquid droplets through:', ['Condensation', 'Evaporation', 'Sublimation', 'Deposition'], 'A', 'easy'),
  s('sci', 'competitive-science', 23, 'The study of fossils is called:', ['Paleontology', 'Entomology', 'Ornithology', 'Ichthyology'], 'A', 'medium'),
  s('sci', 'competitive-science', 24, 'Which one is a renewable energy source?', ['Solar', 'Coal', 'Natural gas', 'Petroleum'], 'A', 'easy'),
  s('sci', 'competitive-science', 25, 'Which hormone regulates blood glucose?', ['Insulin', 'Adrenaline', 'Thyroxine', 'Melatonin'], 'A', 'medium'),
];

export const STATIC_CHEMISTRY: Question[] = [
  s('chem', 'competitive-chemistry', 1, 'Atomic number represents:', ['Number of protons', 'Number of neutrons only', 'Mass number only', 'Number of electrons only'], 'A', 'easy'),
  s('chem', 'competitive-chemistry', 2, 'pH of pure water at 25°C is:', ['7', '14', '0', '1'], 'A', 'easy'),
  s('chem', 'competitive-chemistry', 3, 'Which gas causes acid rain primarily?', ['SO₂ / NOₓ emissions leading to acidic deposition', 'Oxygen', 'Nitrogen only', 'Neon'], 'A', 'medium'),
  s('chem', 'competitive-chemistry', 4, 'Valency of carbon is:', ['4', '2', '3', '1'], 'A', 'easy'),
  s('chem', 'competitive-chemistry', 5, 'Which separation technique uses differences in boiling points?', ['Distillation', 'Chromatography only', 'Filtration only', 'Magnetic separation'], 'A', 'easy'),
  s('chem', 'competitive-chemistry', 6, 'Which metal is liquid at room temperature?', ['Mercury', 'Sodium', 'Iron', 'Aluminium'], 'A', 'easy'),
  s('chem', 'competitive-chemistry', 7, 'NaCl is formed by:', ['Ionic bonding', 'Covalent bonding only', 'Metallic bonding only', 'Hydrogen bonding only'], 'A', 'easy'),
  s('chem', 'competitive-chemistry', 8, 'Which allotrope of carbon is hardest?', ['Diamond', 'Graphite', 'Fullerene', 'Carbon black'], 'A', 'easy'),
  s('chem', 'competitive-chemistry', 9, 'Which indicator turns red in acidic medium?', ['Litmus', 'Phenolphthalein (pink)', 'Starch', 'Methyl orange always neutral'], 'A', 'medium'),
  s('chem', 'competitive-chemistry', 10, 'Rust is mainly:', ['Hydrated iron oxide', 'Iron chloride', 'Iron nitrate', 'Pure iron'], 'A', 'medium'),
  s('chem', 'competitive-chemistry', 11, 'Which gas is known as laughing gas?', ['N₂O', 'NO₂', 'NH₃', 'Ne'], 'A', 'medium'),
  s('chem', 'competitive-chemistry', 12, 'Which acid is present in vinegar?', ['Acetic acid', 'Citric acid', 'Sulfuric acid', 'Nitric acid'], 'A', 'easy'),
  s('chem', 'competitive-chemistry', 13, 'Avogadro’s number is approximately:', ['6.022×10²³ mol⁻¹', '9.81', '3×10⁸', '22.4'], 'A', 'medium'),
  s('chem', 'competitive-chemistry', 14, 'Which salt is used in cooking as common salt?', ['NaCl', 'KNO₃', 'CaCO₃', 'Na₂CO₃'], 'A', 'easy'),
  s('chem', 'competitive-chemistry', 15, 'Which gas supports combustion?', ['Oxygen', 'Nitrogen', 'CO₂ only', 'Helium'], 'A', 'easy'),
  s('chem', 'competitive-chemistry', 16, 'Which metal reacts vigorously with cold water?', ['Sodium', 'Gold', 'Silver', 'Copper'], 'A', 'medium'),
  s('chem', 'competitive-chemistry', 17, 'Which compound is bleaching powder?', ['Ca(OCl)Cl', 'CaCO₃', 'CaSO₄', 'Ca(OH)₂'], 'A', 'hard'),
  s('chem', 'competitive-chemistry', 18, 'Which organic compound family ends with “-ol”?', ['Alcohols', 'Aldehydes', 'Carboxylic acids', 'Alkanes'], 'A', 'medium'),
  s('chem', 'competitive-chemistry', 19, 'Which process converts vapour to liquid?', ['Condensation', 'Evaporation', 'Sublimation', 'Fusion'], 'A', 'easy'),
  s('chem', 'competitive-chemistry', 20, 'Which particle has negligible mass in atom?', ['Electron', 'Proton', 'Neutron', 'Nucleus'], 'A', 'easy'),
  s('chem', 'competitive-chemistry', 21, 'Which acid is known as oil of vitriol?', ['H₂SO₄', 'HCl', 'HNO₃', 'H₃PO₄'], 'A', 'medium'),
  s('chem', 'competitive-chemistry', 22, 'Which catalyst is used in Haber process?', ['Iron', 'Nickel only', 'Platinum only', 'Copper'], 'A', 'hard'),
  s('chem', 'competitive-chemistry', 23, 'Which bond exists in water?', ['Polar covalent', 'Pure ionic only', 'Metallic only', 'Coordinate only'], 'A', 'medium'),
  s('chem', 'competitive-chemistry', 24, 'Which metal is extracted by electrolysis of alumina?', ['Aluminium', 'Iron', 'Zinc', 'Lead'], 'A', 'medium'),
  s('chem', 'competitive-chemistry', 25, 'Which indicator gives pink colour in basic medium?', ['Phenolphthalein', 'Litmus (red in acid)', 'Starch–iodide only', 'Methyl orange (acid form)'], 'A', 'medium'),
];

export const STATIC_ENGLISH: Question[] = [
  s('eng', 'competitive-english', 1, 'Choose the correct spelling:', ['Necessary', 'Neccessary', 'Necessery', 'Necassary'], 'A', 'easy'),
  s('eng', 'competitive-english', 2, 'Synonym of “BRAVE”:', ['Courageous', 'Cowardly', 'Timid', 'Afraid'], 'A', 'easy'),
  s('eng', 'competitive-english', 3, 'Antonym of “GENEROUS”:', ['Stingy', 'Kind', 'Liberal', 'Charitable'], 'A', 'easy'),
  s('eng', 'competitive-english', 4, 'Fill in the blank: She _____ working here since 2020.', ['has been', 'is', 'was', 'were'], 'A', 'medium'),
  s('eng', 'competitive-english', 5, 'Plural of “analysis”:', ['Analyses', 'Analysises', 'Analyzes-only-plural-wrong', 'Analysis'], 'A', 'medium'),
  s('eng', 'competitive-english', 6, 'Correct article: _____ honest man', ['An', 'A', 'The', 'No article'], 'A', 'easy'),
  s('eng', 'competitive-english', 7, 'Passive voice of “They completed the task.”', ['The task was completed by them.', 'The task completed them.', 'They was completed the task.', 'The task had completing by them.'], 'A', 'medium'),
  s('eng', 'competitive-english', 8, 'Choose correctly punctuated:', ["It's raining.", 'Its raining.', 'Its’ raining.', 'It raining.'], 'A', 'easy'),
  s('eng', 'competitive-english', 9, 'Meaning of “Ubiquitous”:', ['Present everywhere', 'Rare', 'Ancient', 'Tiny'], 'A', 'hard'),
  s('eng', 'competitive-english', 10, 'Identify error: Neither of the boys were ready.', ['were → was', 'Neither → Either', 'boys → boy', 'ready → readiness'], 'A', 'medium'),
  s('eng', 'competitive-english', 11, 'Synonym of “Prudent”:', ['Wise/cautious', 'Reckless', 'Lazy', 'Angry'], 'A', 'medium'),
  s('eng', 'competitive-english', 12, 'Indirect speech: He said, “I am tired.”', ['He said that he was tired.', 'He says he was tired.', 'He said that he is tired.', 'He told he tired.'], 'A', 'medium'),
  s('eng', 'competitive-english', 13, 'Choose correct conjunction: _____ it was cold, we went out.', ['Although', 'Because', 'Therefore', 'Hence'], 'A', 'easy'),
  s('eng', 'competitive-english', 14, 'Which is a gerund?', ['Swimming', 'Quickly', 'Beautiful', 'Happy'], 'A', 'medium'),
  s('eng', 'competitive-english', 15, 'Correct usage:', ['Fewer mistakes', 'Less mistakes', 'Little mistakes', 'Much mistakes'], 'A', 'medium'),
  s('eng', 'competitive-english', 16, 'Opposite of “Obsolete”:', ['Current/modern', 'Ancient only', 'Broken', 'Slow'], 'A', 'medium'),
  s('eng', 'competitive-english', 17, 'Fill in: If I _____ you, I would apologize.', ['were', 'was', 'am', 'be'], 'A', 'medium'),
  s('eng', 'competitive-english', 18, 'Which sentence is correct?', ['Neither John nor Mary knows.', 'Neither John nor Mary know.', 'Neither John or Mary knows.', 'Neither John nor Mary knowing.'], 'A', 'medium'),
  s('eng', 'competitive-english', 19, 'Meaning of “Ephemeral”:', ['Short-lived', 'Eternal', 'Heavy', 'Bright'], 'A', 'hard'),
  s('eng', 'competitive-english', 20, 'Choose correct tag: Open the door, _____?', ["won't you", "don't you", 'isn’t it', 'does it'], 'A', 'medium'),
  s('eng', 'competitive-english', 21, 'Synonym of “Eloquent”:', ['Fluent/expressive', 'Silent', 'Rude', 'Shy'], 'A', 'medium'),
  s('eng', 'competitive-english', 22, 'Choose correct spelling:', ['Accommodation', 'Acomodation', 'Accomodation', 'Acommodation'], 'A', 'easy'),
  s('eng', 'competitive-english', 23, 'Which word is an adverb?', ['Quickly', 'Quick', 'Quicken', 'Quickness'], 'A', 'easy'),
  s('eng', 'competitive-english', 24, 'Fill in: She prefers tea _____ coffee.', ['to', 'than', 'over then', 'against'], 'A', 'easy'),
  s('eng', 'competitive-english', 25, 'Which is a compound sentence?', ['He studied hard and he passed.', 'Because he studied.', 'Running fast.', 'Although tired.'], 'A', 'medium'),
];

export const STATIC_COMPUTER: Question[] = [
  s('cs', 'competitive-computer', 1, 'CPU stands for:', ['Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Core Peripheral Unit'], 'A', 'easy'),
  s('cs', 'competitive-computer', 2, 'RAM is:', ['Volatile memory', 'Permanent ROM storage', 'Optical disk', 'Printer buffer'], 'A', 'easy'),
  s('cs', 'competitive-computer', 3, 'Which is an operating system?', ['Linux', 'Microsoft Word', 'Chrome browser only', 'JPEG image format'], 'A', 'easy'),
  s('cs', 'competitive-computer', 4, 'HTTP stands for:', ['HyperText Transfer Protocol', 'High Transfer Text Protocol', 'Hyperlink Transmission Protocol', 'Host Text Tunnel Protocol'], 'A', 'easy'),
  s('cs', 'competitive-computer', 5, 'Which device is input?', ['Keyboard', 'Monitor', 'Speaker', 'Printer'], 'A', 'easy'),
  s('cs', 'competitive-computer', 6, 'Binary base is:', ['2', '10', '16', '8'], 'A', 'easy'),
  s('cs', 'competitive-computer', 7, '1 KB equals:', ['1024 bytes', '1000 bits', '512 bytes', '2048 bits'], 'A', 'easy'),
  s('cs', 'competitive-computer', 8, 'Which typically stores BIOS/firmware?', ['ROM', 'Volatile RAM only', 'CPU registers only', 'GPU framebuffer'], 'A', 'easy'),
  s('cs', 'competitive-computer', 9, 'Malware that self-replicates across networks:', ['Worm', 'Benign cookie file', 'Firewall rule', 'Router NAT table'], 'A', 'medium'),
  s('cs', 'competitive-computer', 10, 'SQL is mainly used for:', ['Relational databases', 'Bitmap graphics', 'Audio synthesis', 'Physical cabling'], 'A', 'easy'),
  s('cs', 'competitive-computer', 11, 'HTTPS commonly adds:', ['TLS encryption on HTTP', 'Lossless-only compression', 'Extra RAM sticks', 'CPU overclocking'], 'A', 'medium'),
  s('cs', 'competitive-computer', 12, 'DNS primarily translates:', ['Hostnames to IP addresses', 'Emails to SMS', 'Lossy PNG conversion', 'GPU shaders'], 'A', 'medium'),
  s('cs', 'competitive-computer', 13, 'Which is secondary storage?', ['SSD', 'CPU L1 cache', 'DRAM row buffer', 'Register file'], 'A', 'easy'),
  s('cs', 'competitive-computer', 14, 'LAN stands for:', ['Local Area Network', 'Large Allocation Node', 'Linked Audio Nest', 'Latency Assignment Number'], 'A', 'easy'),
  s('cs', 'competitive-computer', 15, 'Ctrl+C in most editors:', ['Copy selection', 'Paste clipboard', 'Print dialog', 'Force shutdown'], 'A', 'easy'),
  s('cs', 'competitive-computer', 16, 'In TCP/IP conceptual layering, routing is chiefly handled by:', ['Internet layer / network layer', 'Physical cabling color only', 'SMTP protocol only', 'JPEG codec'], 'A', 'medium'),
  s('cs', 'competitive-computer', 17, 'Which is commonly open-source?', ['Ubuntu Linux', 'Retail-only bundled OEM trial OS', 'Closed-source proprietary firmware blob only', 'Licensed DRM-only kernel'], 'A', 'easy'),
  s('cs', 'competitive-computer', 18, 'Phishing attempts typically:', ['Impersonate trusted sites to steal credentials', 'Improve DNS TTL accuracy', 'Compress PNG losslessly always', 'Cool CPUs physically'], 'A', 'easy'),
  s('cs', 'competitive-computer', 19, 'IPv4 address size:', ['32 bits', '128 bits (IPv6)', '48 bits Ethernet-only claim', '16 bits'], 'A', 'medium'),
  s('cs', 'competitive-computer', 20, 'Key cloud trait:', ['Elastic scaling / pooled resources', 'Requires fixed bare-metal always', 'Single desktop only', 'Cannot use networks'], 'A', 'medium'),
  s('cs', 'competitive-computer', 21, 'GUI stands for:', ['Graphical User Interface', 'General Unix Installer', 'Gateway Utility Index', 'Global Unicode Identifier'], 'A', 'easy'),
  s('cs', 'competitive-computer', 22, 'SMTP is chiefly for:', ['Sending email between servers/clients', 'Streaming MP4 video always', 'SSH tunnels only', 'Bluetooth pairing'], 'A', 'medium'),
  s('cs', 'competitive-computer', 23, 'CPU cache sits:', ['Closer to cores than DRAM', 'Inside HDD spindle motor', 'Printer toner cartridge', 'CRT phosphor'], 'A', 'medium'),
  s('cs', 'competitive-computer', 24, 'Typical compressed archive extension:', ['.zip', '.bmp palette-only doc', '.wav midi hybrid', '.exe certificate CA'], 'A', 'easy'),
  s('cs', 'competitive-computer', 25, 'Firewall primarily:', ['Enforces traffic policies / filtering', 'Increases thermal paste conductivity', 'Formats disks silently nightly', 'Translates Kotlin to JVM bytecode'], 'A', 'easy'),
];
